[2024-03-10T14:21:41.563+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: processing.Create_merge_datasets_1 manual__2024-03-10T14:21:29.946494+00:00 [queued]>
[2024-03-10T14:21:41.572+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: processing.Create_merge_datasets_1 manual__2024-03-10T14:21:29.946494+00:00 [queued]>
[2024-03-10T14:21:41.573+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-10T14:21:41.586+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): Create_merge_datasets_1> on 2024-03-10 14:21:29.946494+00:00
[2024-03-10T14:21:41.592+0000] {standard_task_runner.py:60} INFO - Started process 2888 to run task
[2024-03-10T14:21:41.595+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'processing', 'Create_merge_datasets_1', 'manual__2024-03-10T14:21:29.946494+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/process_data.py', '--cfg-path', '/tmp/tmplyoz5mza']
[2024-03-10T14:21:41.597+0000] {standard_task_runner.py:88} INFO - Job 137: Subtask Create_merge_datasets_1
[2024-03-10T14:21:41.615+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-10T14:21:41.657+0000] {task_command.py:423} INFO - Running <TaskInstance: processing.Create_merge_datasets_1 manual__2024-03-10T14:21:29.946494+00:00 [running]> on host 81bb4583c109
[2024-03-10T14:21:41.743+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='processing' AIRFLOW_CTX_TASK_ID='Create_merge_datasets_1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T14:21:29.946494+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T14:21:29.946494+00:00'
[2024-03-10T14:21:42.339+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-10T14:21:42.349+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=processing, task_id=Create_merge_datasets_1, execution_date=20240310T142129, start_date=20240310T142141, end_date=20240310T142142
[2024-03-10T14:21:42.369+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-10T14:21:42.388+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
