[2024-03-10T16:24:29.183+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: processing.Create_merge_datasets_4 manual__2024-03-10T16:24:12.612238+00:00 [queued]>
[2024-03-10T16:24:29.194+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: processing.Create_merge_datasets_4 manual__2024-03-10T16:24:12.612238+00:00 [queued]>
[2024-03-10T16:24:29.196+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-10T16:24:29.216+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): Create_merge_datasets_4> on 2024-03-10 16:24:12.612238+00:00
[2024-03-10T16:24:29.224+0000] {standard_task_runner.py:60} INFO - Started process 468 to run task
[2024-03-10T16:24:29.233+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'processing', 'Create_merge_datasets_4', 'manual__2024-03-10T16:24:12.612238+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/process_data.py', '--cfg-path', '/tmp/tmp8lpont8g']
[2024-03-10T16:24:29.243+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask Create_merge_datasets_4
[2024-03-10T16:24:29.266+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-10T16:24:29.363+0000] {task_command.py:423} INFO - Running <TaskInstance: processing.Create_merge_datasets_4 manual__2024-03-10T16:24:12.612238+00:00 [running]> on host 65d624ba7e11
[2024-03-10T16:24:29.511+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='processing' AIRFLOW_CTX_TASK_ID='Create_merge_datasets_4' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T16:24:12.612238+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T16:24:12.612238+00:00'
[2024-03-10T16:24:29.831+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/process_data.py:53 DtypeWarning: Columns (10,17) have mixed types. Specify dtype option on import or set low_memory=False.
[2024-03-10T16:24:30.020+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/process_data.py:53 DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
[2024-03-10T16:24:31.110+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-10T16:24:31.127+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=processing, task_id=Create_merge_datasets_4, execution_date=20240310T162412, start_date=20240310T162429, end_date=20240310T162431
[2024-03-10T16:24:31.175+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-10T16:24:31.217+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
